#!/usr/bin/env python3
"""
The device tree an EFI loader hands the kernel, as something a loader can patch.

The kernel expects what m1n1 gives it: a flattened tree with a
simple-framebuffer in it. An EFI application knows those numbers only at run
time, from the firmware, so the tree cannot be written out in full here - but
neither should it be assembled a field at a time in assembly, which is a
flattened-tree writer nobody needs twice.

So this emits the tree with the numbers left blank, and the byte offsets of the
blanks beside it. The loader fills in four values and hands it over. What is
generated rather than written by hand is the part that is a wire format, which
is the same reasoning as tools/mkfdt.py: a reader tested against what its
author imagined is a description of the author's imagination, and a *writer*
hand-assembled in a language with no structs is worse.
"""

import struct
import sys

strings, offsets = bytearray(), {}
st = bytearray()
mark = {}


def soff(name):
    if name not in offsets:
        offsets[name] = len(strings)
        strings.extend(name.encode() + b"\0")
    return offsets[name]


def u32(v):
    st.extend(struct.pack(">I", v))


def begin(name):
    u32(1)
    b = name.encode() + b"\0"
    while len(b) % 4:
        b += b"\0"
    st.extend(b)


def prop(name, data, tag=None):
    u32(3)
    u32(len(data))
    u32(soff(name))
    if tag:
        mark[tag] = len(st)
    d = bytearray(data)
    while len(d) % 4:
        d.append(0)
    st.extend(d)


def main(out, inc):
    begin("")
    prop("#address-cells", struct.pack(">I", 2))
    prop("#size-cells", struct.pack(">I", 2))
    prop("compatible", b"armedit,efi\0")

    # Where memory begins and how much there is comes from the firmware's own
    # map, so this too is left blank. A kernel handed a tree with no memory
    # node has to guess, and the whole point of a handover is that it does not.
    begin("memory@0")
    prop("device_type", b"memory\0")
    prop("reg", struct.pack(">QQ", 0, 0), "mem")
    u32(2)

    # Where the framebuffer is is decided at run time, so the node is written
    # with room for it and the loader writes the numbers in.
    begin("chosen")
    begin("framebuffer@0")
    prop("compatible", b"simple-framebuffer\0")
    prop("reg", struct.pack(">QQ", 0, 0), "reg")
    prop("width", struct.pack(">I", 0), "width")
    prop("height", struct.pack(">I", 0), "height")
    prop("stride", struct.pack(">I", 0), "stride")
    prop("format", b"x8r8g8b8\0")
    u32(2)
    u32(2)
    u32(2)
    u32(9)

    hdr_size = 40
    rsv = struct.pack(">QQ", 0, 0)
    off_rsv = hdr_size
    off_st = off_rsv + len(rsv)
    off_str = off_st + len(st)
    total = off_str + len(strings)
    hdr = struct.pack(">10I", 0xD00DFEED, total, off_st, off_str, off_rsv,
                      17, 16, 0, len(strings), len(st))
    blob = hdr + rsv + bytes(st) + bytes(strings)

    with open(out, "w") as f:
        print("/* Generated by tools/mkefidtb.py - do not edit. */", file=f)
        print('        .section .data,"dw"', file=f)
        print("        .p2align 3", file=f)
        print("        .globl efi_dtb", file=f)
        print("efi_dtb:", file=f)
        for i in range(0, len(blob), 16):
            print("        .byte " + ", ".join(str(b) for b in blob[i:i + 16]), file=f)
        print("        .p2align 3", file=f)

    # The offsets go in a header rather than beside the bytes, because the
    # loader needs them while it is being assembled and the bytes are in a
    # different file by then.
    with open(inc, "w") as f:
        print("/* Generated by tools/mkefidtb.py - do not edit. */", file=f)
        print("#define EFI_DTB_LEN %d" % len(blob), file=f)
        for tag, at in mark.items():
            print("#define EFI_DTB_%s %d" % (tag.upper(), off_st + at), file=f)
    print("mkefidtb: %d bytes, %d patch points" % (len(blob), len(mark)),
          file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
