#!/usr/bin/env python3
"""
Emit a device tree with a simple-framebuffer in it, as assembly.

This is what m1n1 hands a Linux-style image, and what a great many arm64
loaders hand anything: the framebuffer they have already started, described in
the form everyone else uses.

Generated rather than checked in, and a real blob rather than a mocked parser,
because the flattened device tree is a wire format. A reader tested against
only what its author imagined is not a reader - it is a description of the
author's imagination, and the first real machine disagrees with it.
"""

import struct
import sys

strings, offsets = bytearray(), {}


def soff(name):
    if name not in offsets:
        offsets[name] = len(strings)
        strings.extend(name.encode() + b"\0")
    return offsets[name]


st = bytearray()


def u32(v):
    st.extend(struct.pack(">I", v))


def begin(name):
    u32(1)
    b = name.encode() + b"\0"
    while len(b) % 4:
        b += b"\0"
    st.extend(b)


def prop(name, data):
    u32(3)
    u32(len(data))
    u32(soff(name))
    d = bytearray(data)
    while len(d) % 4:
        d.append(0)
    st.extend(d)


def main(out, apple=False):
    begin("")
    prop("#address-cells", struct.pack(">I", 2))
    prop("#size-cells", struct.pack(">I", 2))
    if apple:
        # Shaped like the tree m1n1 actually hands over, which differs from
        # QEMU's in every way that has ever caused a bug here.
        prop("compatible", b"apple,j274\0apple,t8103\0apple,arm-platform\0")

        # Memory above the thirty-second bit. This is the one that decides
        # whether the addresses below are read as addresses or as the low half
        # of one, and a machine whose RAM starts at 0x40000000 cannot ask the
        # question at all.
        begin("memory@10000000000")
        prop("device_type", b"memory\0")
        prop("reg", struct.pack(">QQ", 0x10_0000_0000, 0x2_0000_0000))
        u32(2)

        begin("serial@235200000")
        prop("compatible", b"apple,t8103-uart\0apple,s5l-uart\0")
        prop("reg", struct.pack(">QQ", 0x235200000, 0x4000))
        u32(2)
        # The watchdog, which is how a machine with no PSCI restarts. Its
        # compatible is a list, specific first, exactly as a real Apple tree
        # writes it - the reader has to find the general half inside the list
        # rather than matching the whole property, and a single-string node
        # would not have asked it to.
        begin("watchdog@23d2b0000")
        prop("compatible", b"apple,t8103-wdt\0apple,wdt\0")
        prop("reg", struct.pack(">QQ", 0x23D2B0000, 0x4000))
        u32(2)

        # And the framebuffer where m1n1 leaves it: inside /chosen, not at the
        # root, with a compatible list whose general half is the one anybody
        # else's reader matches. Both of those are how the real tree is written
        # and neither is how QEMU writes one, so a parser that only ever met
        # QEMU has not been asked either question.
        begin("chosen")
        prop("bootargs", b"\0")
        begin("framebuffer@9e0e40000")
        prop("compatible", b"apple,simple-framebuffer\0simple-framebuffer\0")
        prop("reg", struct.pack(">QQ", 0x9_E0E4_0000, 0x1_0000_00))
        prop("width", struct.pack(">I", 1512))
        prop("height", struct.pack(">I", 982))
        prop("stride", struct.pack(">I", 6144))
        prop("format", b"x2r10g10b10\0")
        u32(2)      # end framebuffer
        u32(2)      # end chosen
        u32(2)      # end root
        u32(9)
    else:
        begin("framebuffer@9c000000")
        prop("compatible", b"simple-framebuffer\0")
        prop("reg", struct.pack(">QQ", 0x9C000000, 0x1000000))
        prop("width", struct.pack(">I", 1512))
        prop("height", struct.pack(">I", 982))
        prop("stride", struct.pack(">I", 6144))
        prop("format", b"x2r10g10b10\0")
        u32(2)      # end framebuffer
        u32(2)      # end root
        u32(9)      # end of the tree

    hdr_size = 40
    off_struct = hdr_size
    off_strings = off_struct + len(st)
    total = off_strings + len(strings)
    hdr = struct.pack(">IIIIIIIIII", 0xD00DFEED, total, off_struct, off_strings,
                      hdr_size, 17, 16, 0, len(strings), len(st))
    blob = bytes(hdr) + bytes(st) + bytes(strings)

    name = "fdt_apple" if apple else "fdt_sample"
    lines = ['#include "asm.inc"',
             "/* Generated by tools/mkfdt.py - a device tree with a screen in it. */",
             "        RODATA",
             "        .p2align 3",
             "        .globl  SYM(%s)" % name,
             "SYM(%s):" % name]
    for at in range(0, len(blob), 16):
        lines.append("        .byte   "
                     + ", ".join("0x%02X" % b for b in blob[at:at + 16]))
    open(out, "w").write("\n".join(lines) + "\n")
    print("mkfdt: %d bytes" % len(blob), file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1], "--apple" in sys.argv)
