#!/usr/bin/env python3
"""
Emit a device tree with a simple-framebuffer in it, as assembly.

This is what m1n1 hands a Linux-style image, and what a great many arm64
loaders hand anything: the framebuffer they have already started, described in
the form everyone else uses.

Generated rather than checked in, and a real blob rather than a mocked parser,
because the flattened device tree is a wire format. A reader tested against
only what its author imagined is not a reader - it is a description of the
author's imagination, and the first real machine disagrees with it.
"""

import struct
import sys

strings, offsets = bytearray(), {}


def soff(name):
    if name not in offsets:
        offsets[name] = len(strings)
        strings.extend(name.encode() + b"\0")
    return offsets[name]


st = bytearray()


def u32(v):
    st.extend(struct.pack(">I", v))


def begin(name):
    u32(1)
    b = name.encode() + b"\0"
    while len(b) % 4:
        b += b"\0"
    st.extend(b)


def prop(name, data):
    u32(3)
    u32(len(data))
    u32(soff(name))
    d = bytearray(data)
    while len(d) % 4:
        d.append(0)
    st.extend(d)


def main(out):
    begin("")
    prop("#address-cells", struct.pack(">I", 2))
    prop("#size-cells", struct.pack(">I", 2))
    begin("framebuffer@9c000000")
    prop("compatible", b"simple-framebuffer\0")
    prop("reg", struct.pack(">QQ", 0x9C000000, 0x1000000))
    prop("width", struct.pack(">I", 1512))
    prop("height", struct.pack(">I", 982))
    prop("stride", struct.pack(">I", 6144))
    prop("format", b"x2r10g10b10\0")
    u32(2)          # end framebuffer
    u32(2)          # end root
    u32(9)          # end of the tree

    hdr_size = 40
    off_struct = hdr_size
    off_strings = off_struct + len(st)
    total = off_strings + len(strings)
    hdr = struct.pack(">IIIIIIIIII", 0xD00DFEED, total, off_struct, off_strings,
                      hdr_size, 17, 16, 0, len(strings), len(st))
    blob = bytes(hdr) + bytes(st) + bytes(strings)

    lines = ['#include "asm.inc"',
             "/* Generated by tools/mkfdt.py - a device tree with a screen in it. */",
             "        RODATA",
             "        .p2align 3",
             "        .globl  SYM(fdt_sample)",
             "SYM(fdt_sample):"]
    for at in range(0, len(blob), 16):
        lines.append("        .byte   "
                     + ", ".join("0x%02X" % b for b in blob[at:at + 16]))
    open(out, "w").write("\n".join(lines) + "\n")
    print("mkfdt: %d bytes" % len(blob), file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1])
