#!/usr/bin/env python3
"""
Bake the approved operations into the image.

`ops/` holds what the consortium agreed to ship: machine code, its source, and
the votes. That is enough for a person to review and not enough for the editor
to use - a blob in a directory is not a blob the running program can find, and
on bare metal there is no directory to look in.

So the blobs become a table in the binary. The editor gets them the way it gets
its font: linked in, present before the first instruction runs, and available
with no network, no filesystem, and no backend. That is the whole point of
compiling operations ahead of time - "colours blue" should work on a laptop
with the wifi off and on a machine that has never had an operating system.

The pattern is rewritten on the way through. The server's patterns carry types
- {name:colour} accepts a colour and {n:num} an integer - and the type is what
decides whether a script is specific enough to exist at all. That decision has
already been made by the time a blob is approved, and the device cannot re-make
it: it has no colour table and no list of languages, and shipping one would be
shipping the same judgement twice in two places that can disagree. What the
device needs is arity, so:

    colours {name:colour}   ->   colours {}      one word
    explain {this:words}    ->   explain {*}     one or more

An operation that matches on the device and then produces nothing has declined,
which is exactly what it would have done on the server, so the narrower type
check costs correctness nothing: the operation still refuses what it refuses.
"""

import os
import re
import sys

# The kinds that bind exactly one word. Anything else takes the rest.
ONE_WORD = {"word", "num", "lang", "colour", "color"}


def parse(path):
    """Read one .op file into the fields the table needs."""
    fields, body = {}, open(path).read()
    for line in body.split("\n"):
        m = re.match(r"^(name|matches|arguments|bytes|sha|author)\s+(.*)$", line)
        if m:
            fields[m.group(1)] = m.group(2).strip()
    if "name" not in fields or "matches" not in fields:
        raise SystemExit("%s: no name or no pattern" % path)
    return fields


def device_pattern(pattern):
    """Types out, arity in. Returns the rewritten pattern and its variable count."""
    count = 0
    out = []
    for token in pattern.split():
        m = re.match(r"^\{([A-Za-z0-9_]+)(?::([A-Za-z]+))?\}$", token)
        if not m:
            out.append(token)
            continue
        count += 1
        kind = (m.group(2) or "words").lower()
        out.append("{}" if kind in ONE_WORD else "{*}")
    return " ".join(out), count


def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main(opsdir, out):
    entries = []
    for name in sorted(os.listdir(opsdir)):
        if not name.endswith(".op"):
            continue
        meta = parse(os.path.join(opsdir, name))
        blob = os.path.join(opsdir, name[:-3] + ".bin")
        if not os.path.exists(blob):
            # The metadata without the code is not an operation, and pretending
            # otherwise would put an entry in the table that cannot run.
            print("mkops: %s has no machine code, skipped" % name, file=sys.stderr)
            continue
        code = open(blob, "rb").read()
        pattern, nvars = device_pattern(meta["matches"])
        entries.append((meta["name"], pattern, nvars, code))

    f = open(out, "w")
    f.write('#include "asm.inc"\n')
    f.write("/*\n * Generated by tools/mkops.py from ops/ - do not edit.\n")
    f.write(" *\n * The operations this build ships with, and can run with no network.\n */\n")
    f.write("        RODATA\n        .p2align 3\n")

    for i, (name, pattern, nvars, code) in enumerate(entries):
        f.write('op%d_name:    .asciz "%s"\n' % (i, escape(name)))
        f.write('op%d_pattern: .asciz "%s"\n' % (i, escape(pattern)))
        f.write("        .p2align 2\n")
        f.write("op%d_code:\n" % i)
        for at in range(0, len(code), 16):
            row = ", ".join("0x%02X" % b for b in code[at:at + 16])
            f.write("        .byte   %s\n" % row)
        f.write("op%d_end:\n\n" % i)

    # Offsets from the table, not addresses.
    #
    # A table of pointers needs a relocation per entry, and Mach-O refuses
    # relocations in a read-only section - so absolute addresses would mean
    # putting the operation table, function pointers and all, in writable
    # memory. A difference between two symbols in the same section is folded at
    # assembly time and needs no relocation at all, which keeps the table
    # const on both targets and costs one add at use.
    f.write("        .p2align 3\n")
    f.write("        .globl  SYM(ops_builtin)\n")
    f.write("SYM(ops_builtin):\n")
    for i, (name, pattern, nvars, code) in enumerate(entries):
        f.write("        .long   op%d_name - SYM(ops_builtin)\n" % i)
        f.write("        .long   op%d_pattern - SYM(ops_builtin)\n" % i)
        f.write("        .long   %d\n" % nvars)
        f.write("        .long   op%d_code - SYM(ops_builtin)\n" % i)
        f.write("        .long   op%d_end - op%d_code\n" % (i, i))
    # Realign before the count.
    #
    # Records are five 4-byte fields, so a table of an odd number of them
    # leaves the next symbol 4-aligned and not 8. Loading a .quad from there
    # is an unaligned 64-bit access, which on a hosted target is invisible and
    # on bare metal with the MMU off is a data abort - the kernel faulted on
    # its first offline request, at exactly one operation in the table.
    f.write("\n        .p2align 3\n")
    f.write("        .globl  SYM(ops_builtin_count)\n")
    f.write("SYM(ops_builtin_count):\n        .quad   %d\n" % len(entries))
    f.close()
    print("mkops: %d operation(s) baked in" % len(entries), file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
